### ISSUE TITLE
Task 1.10: Populate Quality Attributes Tree

### ISSUE THREAD

**Issue by joshuag1214** [joshuag1214/ENPM613-Project#10]
In addition to security scenarios and requirements identified in previous tasks, also identify the other
quality attributes and respective scenarios for the software to be developed. For each
identified scenario:
  a. Provide a brief description (one-two sentences)
  b. Assign a number from 1 to 3 (where Low = 1, Medium = 2, High = 3) for its
  utility (importance) to the users
  c. Assign a number from 1 to 3 (where Difficult or high risk = 1, Medium difficulty
  or risk = 2, Rather easy and low risk = 3) for the estimated difficulty or risk to
  implement that scenario
  d. Compute the priority score (utility * difficulty). This score will help you decide
  what scenario will be within the scope of your software for design and
  implementation.
See the provided Requirements Analysis template.

**Comment by trimpinm** [comment]
Currently in progress, Editing quality attributes tree in google drive https://docs.google.com/spreadsheets/d/1FXSQRmMUv06ovWQyozJOEZyO5_XZ1xX_/edit?gid=1390989542#gid=1390989542

**Comment by trimpinm** [comment]
Added Quality attribute tree to Formal Documentation https://docs.google.com/document/d/1pKawat1Op2XIdntfj4kBSuQxXRRJqb6i/edit#heading=h.2jxsxqh
