### ISSUE TITLE
Task 1.11: Prioritize Quality Scenarios

### ISSUE THREAD

**Issue by joshuag1214** [joshuag1214/ENPM613-Project#11]
For the top three highest priority quality scenarios (identified in Task 1.10), provide their description using the SEI
Template (Source of stimulus, Stimulus, Environment, Artifact, Response, Response
measure).

**Comment by trimpinm** [comment]
Dependent on [Task 1.10](https://github.com/joshuag1214/ENPM613-Project/issues/10)

Prioritization of quality attributes identified in 1.10:

https://docs.google.com/document/d/1O6nVKZpNXv_elKWv2L41HfNAD9U_hGiS9DbqdGXw6Uw/edit

**Comment by trimpinm** [comment]
Added SEI Analysis to Formal Document https://docs.google.com/document/d/1pKawat1Op2XIdntfj4kBSuQxXRRJqb6i/edit#heading=h.2jxsxqh
