### ISSUE TITLE
Task 2.2: Develop a user interface flow model

### ISSUE THREAD

**Issue by joshuag1214** [joshuag1214/ENPM613-Project#16]
Develop a user interface flow model, i.e., the high-level relationships between major user
interface elements (screens). Use a User Interface Flow Diagram or a UML state machine
diagram.

**Comment by trimpinm** [comment]
Progress happening here: https://lucid.app/lucidchart/d959b854-5362-4c41-9431-89edb8ccfe0a/edit?invitationId=inv_648f421b-24ff-48d9-9956-9ebfbbe93eba&page=pi2dVMlh-gwc# 

Note from TA: The user interface flow diagram should have separate flows for different user roles (ie. professors, students, administrators) if their interactions with the system vary. 

Certain functionalities, like adding classes, are specific to certain users (in this case, professors). It's essential to capture those unique flows in your diagram. This approach ensures your interface design accurately reflects different user experiences and helps clarify which pages or options are available to each user type

**Comment by joshuag1214** [comment]
will try to finish at least the admin stuff tomorrow

**Comment by trimpinm** [comment]
Professor and Student flow models are ready for review. Let me know when you're done with the Admin one and I'll take a look!

**Comment by joshuag1214** [comment]
![Image](https://github.com/user-attachments/assets/ccca7b39-d1bf-4978-9080-520e507850f8)
Done with Admin. Just skimmed over Professor and Student and made 1 comment about a page type. Will look more in depth tomorrow. Contacted TA/Prof on how depth we should go for options:
![Image](https://github.com/user-attachments/assets/066bfc07-9820-4204-b419-8754f61926fb)

**Comment by trimpinm** [comment]
Thanks for doing that, let me know what the response is! You're right that it wont be a different page, I'm just not sure if we should ignore the user action of Clicking download in that case

**Comment by cpettit98** [comment]
I went ahead and added a few comments in the diagrams! Overall they look really nice - great job. Most of my comments basically said the same thing in different spots so it looks like more than it actually is.

**Comment by joshuag1214** [comment]
Thanks for also checking the diagram. Also this is the Ta's response![Image](https://github.com/user-attachments/assets/3cfc8fac-5e4a-48e7-911c-27896ab9c466)

**Comment by trimpinm** [comment]
@joshuag1214 Thanks for clarifying that, I'll go ahead and update the flows. 
@cpettit98 Thanks for the review, I'll take a look at the personas shortly!
