### ISSUE TITLE
Task 1.4: Identify a list of functional features derived from the use cases

### ISSUE THREAD

**Issue by joshuag1214** [joshuag1214/ENPM613-Project#4]

**Comment by cpettit98** [comment]
This task correlates to section 2.4 Functional Features in the formal documentation for assignment 2 in the google drive. Putting this here to help track info and make sure things get put in the right place.

**Comment by adiwari** [comment]
Ready for review @joshuag1214  @cpettit98 @trimpinm @thefueley
