### ISSUE TITLE
Task 1.7: Identify security scenarios derived from the abuse cases

### ISSUE THREAD

**Issue by joshuag1214** [joshuag1214/ENPM613-Project#7]
Assignment 2, Requirement 7 "Identify security scenarios derived from the abuse cases".

**Comment by thefueley** [comment]
Security scenarios generated from the abuse cases, based on the examples given in class slides. Scenarios developed in a graphical format. [Abuse Use Cases and Scenarios](https://lucid.app/lucidchart/d7bee23c-dc5d-40ea-9522-8844d9091f50/edit?viewport_loc=-167%2C104%2C2247%2C1224%2C.Q4MUjXso07N&invitationId=inv_104928d4-bbd9-4028-a02d-10435a015080)

**Comment by thefueley** [comment]
Need to color code normal workflow and color code the attack workflow

**Comment by thefueley** [comment]
Added color codes to normal flow and attack flow use cases. Ready for review. @joshuag1214 @trimpinm @cpettit98 @adiwari

**Comment by joshuag1214** [comment]
Going to put scenarios as a text in the first page of the use case diagram

**Comment by joshuag1214** [comment]
Finished, ready for review

**Comment by joshuag1214** [comment]
related to task 1.8 (https://github.com/users/joshuag1214/projects/2/views/1?pane=issue&itemId=81129775). Requirements analysis templates excel sheet is updated
